OrdererOrgs:
  - Name: Orderer
    Domain: bc.cip
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: Org1
    Domain: org1.bc.cip
    EnableNodeOUs: true
    CA:
      Specs:
        - Hostname: ca-svc
    Specs:
      - Hostname: peer1
      - Hostname: peer2
    Template:
      Count: 0
    Users:
      Count: 1