OrdererOrgs:
  - Name: Orderer
    Domain: bc.cip
    Specs:
      - Hostname: orderer0.bc.cip
        SANS:
          - 192.168.1.2
      - Hostname: orderer1.bc.cip
        SANS:
          - 192.168.1.3
      - Hostname: orderer2.bc.cip
        SANS:
          - 192.168.1.4

PeerOrgs:
  - Name: Org1MSP
    Domain: org1.bc.cip
    EnableNodeOUs: true
    CA:
      Specs:
        - Hostname: ca1.org1.bc.cip
          SANS:
            - 192.168.1.2
        - Hostname: ca2.org1.bc.cip
          SANS:
            - 192.168.1.3
    Specs:
      - Hostname: peer0
        SANS:
          - 192.168.1.2
      - Hostname: peer1
        SANS:
          - 192.168.1.3
    Template:
      Count: 0
    Users:
      Count: 1