OrdererOrgs:
  - Name: Orderer
    Domain: scd.org.br
    Specs:
      - Hostname: orderer1
        SANS:
          - orderer-svc
          - orderer.scd.org.br
      - Hostname: orderer2
        SANS:
          - orderer-svc
          - orderer.scd.org.br
      - Hostname: orderer3
        SANS:
          - orderer-svc
          - orderer.scd.org.br

PeerOrgs:
  - Name: 04391007
    Domain: scd.org.br
    EnableNodeOUs: true
    CA:
      Specs:
        - Hostname: ca-svc
          SANS:
            - ca.04391007.scd.org.br
    Specs:
      - Hostname: peer1
      - Hostname: peer2
    Template:
      Count: 0
    Users:
      Count: 0