version: '2'

networks:
  ca_network:
  worker2:

services:

  ca2.org1.bc.cip:
    image: ibmblockchain/fabric-ca:$IMAGETAG
    hostname: ca2.org1.bc.cip
    container_name: ca.org1.bc.cip
    environment:
      - LICENSE=accept
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca2.org1.bc.cip
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.bc.cip-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$ORG1CAKEY
      - REP_HOST=192.168.1.2
    ports:
      - "7054:7054"
    command: sh -c 'sleep 30 && fabric-ca-server start -c /etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.bc.cip-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$ORG1CAKEY -b admin:adminpw -d'
    volumes:
      - ../material/crypto-config/peerOrganizations/org1.bc.cip/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../material/CA-Replication/CA2/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml
    depends_on:
      - pg.slave.bc.cip
    networks:
      - ca_network
      - worker2

  pg.slave.bc.cip:
    build: ../material/CA-Replication/CA2/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpw
      - POSTGRES_DB=fabric
      - PG_REP_USER=rep_admin
      - PG_REP_PASSWORD=adminpw
      - PG_REP_HOST=192.168.1.2
    container_name: pg_slave.org1.bc.cip
    ports:
      - "5432:5432"
    networks:
      - ca_network

  zookeeper:
    container_name: zookeeper.bc.cip
    # image: tmeister/zookeeper:latest
    image: ibmblockchain/fabric-zookeeper:$EXTERNALTAG
    restart: always
    environment:
      - LICENSE=accept
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=192.168.1.2:2888:3888 server.2=zookeeper:2888:3888 server.3=192.168.1.4:2888:3888
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - worker2