NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.04391007.hext.scd.org.br-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.04391007.hext.scd.org.br-cert.pem
    OrganizationalUnitIdentifier: peer
