OrdererOrgs:
  - Name: Orderer
    Domain: bc.cip
    Specs:
      - Hostname: orderer0
        SANS:
          - 192.168.1.2
      - Hostname: orderer1
        SANS:
          - 192.168.1.3
      - Hostname: orderer2
        SANS:
          - 192.168.1.4

PeerOrgs:
  - Name: Org1MSP
    Domain: org1.bc.cip
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0
        SANS:
          - 192.168.1.2
          - 192.168.1.3
          - 192.168.1.4

    Template:
      Count: 4
      Start: 1
    Users:
      Count: 0
