version: '2'

services:
  orderer2.bc.cip:
    container_name: orderer2.bc.cip
    image: hyperledger/fabric-orderer:$IMAGETAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[192.168.1.4:9092, 192.168.1.4:10092, 192.168.1.4:11092, 192.168.1.4:12092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer2.bc.cip/msp:/etc/hyperledger/msp/orderer/msp
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer2.bc.cip/tls:/etc/hyperledger/tls/orderer/tls
    depends_on:
      - kafka8
      - kafka9
      - kafka10
      - kafka11

  kafka8:
    container_name: kafka8
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=8
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper2

  kafka9:
    container_name: kafka9
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=9
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 10092:9092
    depends_on:
      - zookeeper2

  kafka10:
    container_name: kafka10
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=10
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 11092:9092
    depends_on:
      - zookeeper2

  kafka11:
    container_name: kafka11
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=11
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 12092:9092
    depends_on:
      - zookeeper2
    
  zookeeper2:
    container_name: zookeeper2
    # image: tmeister/zookeeper:latest
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=192.168.1.2:2888:3888 server.2=192.168.1.3:2888:3888 server.3=zookeeper2:2888:3888
    ports:
      - 4181:2181
      - '2888'
      - '3888'