version: '2'

volumes:
  pg_data:

networks:
  worker1:

services:

  ca1.org1.bc.cip:
    image: hyperledger/fabric-ca:$IMAGETAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca1.org1.bc.cip
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.bc.cip-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/$ORG1CAKEY
      - REP_HOST=localhost
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -c /etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.bc.cip-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/$ORG1CAKEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.bc.cip/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./CA-Replication/CA1/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server-config/fabric-ca-server-config.yaml
    container_name: ca1.org1.bc.cip
    depends_on:
      - pg.master.bc.cip
    networks:
      - worker1

  pg.master.bc.cip:
    build: ./CA-Replication/CA1/
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpw
      - POSTGRES_DB=fabric
      - PG_REP_USER=rep_admin
      - PG_REP_PASSWORD=adminpw
    container_name: pg.master.bc.cip
    ports:
      - "5432:5432"
    networks:
      - worker1

  orderer0.bc.cip:
    container_name: orderer0.bc.cip
    image: hyperledger/fabric-orderer:$IMAGETAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_GENESISPROFILE=ModeKafkaOrderer
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - CONFIGTX_ORDERER_KAFKA_BROKERS=[192.168.1.2:9092, 192.168.1.2:10092, 192.168.1.2:11092, 192.168.1.2:12092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer0.bc.cip/msp:/etc/hyperledger/msp/orderer/msp
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer0.bc.cip/tls:/etc/hyperledger/tls/orderer/tls
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - worker1

  peer0.org1.bc.cip:
    container_name: peer0.org1.bc.cip
    image: hyperledger/fabric-peer:$IMAGETAG
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.bc.cip
      - CORE_PEER_ADDRESS=peer0.org1.bc.cip:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.bc.cip:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bc.cip:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.bc.cip/peers/peer0.org1.bc.cip/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.bc.cip/peers/peer0.org1.bc.cip/tls:/etc/hyperledger/peer/tls
        - ./crypto-config/peerOrganizations/org1.bc.cip/users:/etc/hyperledger/msp/users
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer0.bc.cip/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - orderer0.bc.cip
      - couchdb
    networks:
      - worker1

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:$IMAGETAG
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    networks:
      - worker1

  peer1.org1.bc.cip:
    container_name: peer1.org1.bc.cip
    image: hyperledger/fabric-peer:$IMAGETAG
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.bc.cip
      - CORE_PEER_ADDRESS=peer1.org1.bc.cip:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.bc.cip:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.bc.cip:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel-artifacts/:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.bc.cip/peers/peer1.org1.bc.cip/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.bc.cip/peers/peer1.org1.bc.cip/tls:/etc/hyperledger/peer/tls
        - ./crypto-config/peerOrganizations/org1.bc.cip/users:/etc/hyperledger/msp/users
        - ./crypto-config/ordererOrganizations/bc.cip/orderers/orderer0.bc.cip/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - orderer0.bc.cip
      - couchdb1
    networks:
      - worker1

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:$IMAGETAG
    ports:
      - "6984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    networks:
      - worker1

  zookeeper0:
    container_name: zookeeper0
  # image: tmeister/zookeeper:latest
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=192.168.1.3:2888:3888 server.3=192.168.1.4:2888:3888
    ports:  
      - 2181:2181
      - '2888'
      - '3888'
    depends_on:
      - ca1.org1.bc.cip
    networks:
      - worker1

  kafka0:
    container_name: kafka0
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
    networks:
      - worker1

  kafka1:
    container_name: kafka1
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 10092:9092
    depends_on:
      - zookeeper0
    networks:
      - worker1

  kafka2:
    container_name: kafka2
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 11092:9092
    depends_on:
      - zookeeper0
    networks:
      - worker1

  kafka3:
    container_name: kafka3
    # image: wurstmeister/kafka:latest
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_ZOOKEEPER_CONNECT=192.168.1.2:2181,192.168.1.3:3181,192.168.1.4:4181
    ports:
      - 12092:9092
    depends_on:
      - zookeeper0
    networks:
      - worker1
